base/urls.py
from django.conf.urls import url
from . import views

app_name = 'base'
urlpatterns = [
	url(r'^$',views.index,name="index"),
	url(r'^profile/',views.profile,name="profile"),
]

inventory/urls.py
from django.conf.urls import url
from . import views

app_name = 'inventory'
urlpatterns = [
	url(r'^$',views.index,name="inventory_index"),
	url(r'^update/',views.update,name='update'),
	url(r'^update/.*',views.update,name='update'),
	url(r'^issue/',views.issue,name='issue'),
	url(r'^requests/',views.list_requests,name='requests'),
]

the_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('base.urls', namespace='base_app')),
    url(r'^site/',include('access.urls', namespace='access')),
    url(r'^inventory/',include('inventory.urls', namespace='inventory')),
    url(r'^projects/',include('projects.urls', namespace='projects')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

inventory/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class storage_locations(models.Model):
	location = models.CharField(max_length=30, default='eYantra Lab')

	def __str__(self):
		return(self.location)

class inventory(models.Model):
	bot_name = models.CharField(max_length=20)
	bot_count = models.IntegerField(default=0)
	bot_stored_place = models.ForeignKey(storage_locations, on_delete=models.CASCADE)

	def __str__(self):
		return self.bot_name

class accessories(models.Model):
	successor_bot = models.ForeignKey(inventory,on_delete=models.CASCADE)
	accessory = models.CharField(max_length=30)
	count = models.IntegerField(default=0)
	stored_place = models.ForeignKey(storage_locations,on_delete=models.CASCADE)

	def __str__(self):
		return self.accessory

class issue_application(models.Model):
	request_by = models.ForeignKey(User,on_delete=models.CASCADE)
	subject = models.CharField(max_length=50)
	application = models.CharField(max_length=350)
	passed = models.BooleanField(default=False)
	issued_on = models.DateTimeField('date_issue_requested')

	def __str__(self):
		return self.subject

inventory/forms.py
from django import forms
from .models import storage_locations, inventory, accessories, issue_application

class loc_form(forms.ModelForm):
	class Meta:
		model = storage_locations
		fields = ['location']

class bot_form(forms.ModelForm):
	class Meta:
		model = inventory
		fields = ['bot_name','bot_count']
		exclude = ['bot_stored_place']

class accessory_form(forms.ModelForm):
	class Meta:
		model = accessories
		fields = ['accessory','count']
		exclude = ['successor_bot','stored_place']

class issue_details(forms.ModelForm):
	class Meta:
		model = issue_application
		fields = ['application','subject']
		exclude = ['request_by','issued_on']

inventory/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import auth
from django.contrib.auth.models import User
from itertools import chain
from django.utils import timezone
from . import models
from .forms import loc_form,bot_form, accessory_form, issue_details

# Create your views here.

def index(request):
	data = models.storage_locations.objects.all()
	data_for_page = {'data':data}
	return(render(request,'inventory/index.html',data_for_page))


def update(request): 		# location=None,bot=None,accessory=None):
	if(request.method=='POST'):
		loc_f = loc_form(request.POST)
		bot_f = bot_form(request.POST)
		acc_f = accessory_form(request.POST)
		if((loc_f.is_valid() and bot_f.is_valid()) and acc_f.is_valid()):
			location = models.storage_locations.objects.get(location__iexact=request.POST['location'])
			if(request.POST['choice']=='To update old inventory'):
				l = len(request.POST.getlist('bot_name'))
				for i in range(l):
					bot = models.inventory.objects.get(bot_name=request.POST.getlist('bot_name')[i])
					bot.bot_count = request.POST.getlist('bot_count')[i]
					bot.bot_stored_place = location
					bot.save()
				l = len(request.POST.getlist('accessory'))
				for i in range(l):
					acc = models.accessories.objects.get(accessory__iexact=request.POST.getlist('accessory')[i])
					acc.count = request.POST.getlist('count')[i]
					acc.stored_place = location
					acc.save()
				return(HttpResponseRedirect('/'))
			else:
				if(request.POST['bot_name']!='0'):
					bot = bot_f.save(commit=False)
					bot.bot_stored_place = location
					bot.save()
				if(request.POST['accessory']!='0'):
					accessory = acc_f.save(commit=False)
					accessory.stored_place = location
					bot = models.inventory.objects.get(bot_name__iexact=request.POST['successor_bot'])
					accessory.successor_bot = bot
					accessory.save()
				return(HttpResponseRedirect('/'))
		else:
			lst = [loc_f.errors,bot_f.errors,acc_f.errors]
			return(HttpResponse(lst))

	elif(request.GET.get('location')):
		location = models.storage_locations.objects.get(location__iexact=request.GET['location'])
		if(request.GET['choice']=='To update old inventory'):
			context = {'location':location,'selection0':True,'selection1':True,'choice':'To update old inventory'}
			return(render(request,'inventory/update_old.html',context))
		else:
			context = {'selection0':True,'selection1':True,'selection2':False,'location':location,'choice':'Add new items'}
			return(render(request,'inventory/update_new.html',context))
	elif(request.GET.get('choice')):
		data = models.storage_locations.objects.all()
		context = {'data':data,'selection0':True,'selection1':False}
		if(request.GET['choice']=='old'):
			context['choice'] = 'To update old inventory'
		else:
			context['choice'] = 'Add new items'
		return(render(request,'inventory/update.html',context))
	else:
		context = {'selection0':False,'selection1':False}
		return(render(request,'inventory/update.html',context))



def issue(request):
	if(request.method=='POST'):
		form = issue_details(request.POST)
		if(form.is_valid()):
			appl = form.save(commit=False)
			appl.request_by = request.user
			appl.issued_on = timezone.now()
			appl.save()
			return(HttpResponse("Request initiated"))
		else:
			return(HttpResponse(form.errors))
	else:
		bot_data = models.inventory.objects.all()
		accessory_data = models.accessories.objects.all()
		data = list(chain(bot_data,accessory_data))
		data_for_page = {'data':data}
		return(render(request,'inventory/issue.html',data_for_page))

def list_requests(request):
	if(request.method=='POST'):
		req = models.issue_application.objects.get(id=request.POST['id'])
		req.passed = True
		req.save()
		return(HttpResponseRedirect('inventory/requests'))
	else:
		data = models.issue_application.objects.all()
		data_for_page = {'data':data}
		return(render(request,'inventory/requests.html',data_for_page))

templates/inventory/index.html
{% extends 'base/index.html' %}
{% load static %}
{% block content %}

{% for i in data %}

<div align="center">
   <!--<img  src={% static "assets/logo.png" %} alt="LOGO" style="width:300px;height:172px;">-->
<div class="row" >
         <div class="col s4 offset-s4 valign">
           <div class="card">
             <br>
               <span class="card-title"><h4>Storage Location:- {{i.location}}</h4></span>
             <!-- </div> -->
             <!-- <div class="card-content"> -->
            <div class="row" >
                     <div class="col s10 offset-s1 valign">
            <table class="bordered">
              <thead >
                <tr>
                    <th>Inventory</th>
                    <th>Count</th>
                </tr>
              </thead>

              <tbody>
                <tr>
            {% for j in i.inventory_set.all %}  
                        <td>{{j.bot_name}}</td>
                        <td>{{j.bot_count}}</td>
             {% endfor %}
             </tr>
             <tr >
                {% for k in i.accessories_set.all %}
                        <td>{{k.accessory}}</td>
                        <td>{{k.count}}</td>
             {% endfor %}

                </tr>
               
                
              </tbody>
             </table></div></div>
             </div>
         </div>
       </div>
       </div><br><br>

{% endfor %}
{% endblock %}

templates/inventory/issue.html
{% extends 'base/index.html' %}
{% load static %}
{% block content %}


    <center>
        <h2>
            Enter the required details.
        </h2>
    </center>
    <div class="row">
   <div class="col s4 offset-s4 valign">
    <table class="striped" class="centered">
      <thead>
        <tr>
            <th class="z-depth-5" >Inventory</th>
            <th class="z-depth-5" >Count</th>
        </tr>
      </thead>
        
        {% for i in data %}
      <tbody>
        <tr class="z-depth-5" >
            {% if i.bot_name %}
                <td>{{i.bot_name}}</td>
                <td>{{i.bot_count}}</td>
            {% else %}
                <td>{{i.accessory}}</td>
                <td>{{i.count}}</td>
            {% endif %}
        </tr>
       
        
      </tbody>
        {% endfor %}
    </table>
    </div>
    <!-- </div> -->
    </div>

    

    <div class="row">
          <div class="col s6 offset-s3 valign">
            <div class="card-panel grey lighten-4">
              <center>
                <form method = 'post'>
                    {% csrf_token %}
                    <h3>Select the requirement</h3>
                    
                    <div class="input-field col s12">
                      <i class="material-icons prefix">local_library</i>
                      <input type = 'text' name='subject' placeholder='Subject'><br><br>
                    </div>
                    <div class="row">
                           <div class="input-field col s12">
                             <i class="material-icons prefix">mode_edit</i>
                             <textarea id="icon_prefix2" class="materialize-textarea" type = "text" name="application"></textarea>
                             <label for="icon_prefix2">Enter the issue application here.(max 300)</label>
                           </div>
                         </div>
                    <center>
                    <a href="#"><button type="submit" class="btn waves-effect waves-light">Submit</button>
                      </a></center>
                   
                </form>
            </center>

              
            </div>
          </div>
        </div>



{% endblock %}

templates/inventory/requests.html
{% extends 'base/index.html' %}
{% load static %}
{% block content %}

<center>
    <h2>
        ALL Requests left.
    </h2>
<h3>PENDING REQUESTS</h3>
</center>
<br>
        {% for i in data %}

        {% if not i.passed %}
        <div align="center">
        <div class="row" >
                 <div class="col s4 offset-s4 valign">
                   <div class="card"><br>
                       <span class="card-title"><h5>Subject :- {{i.subject}} </h5></span>
                     <div class="card-content">
                         <div class="card-action">
                           <a class ="modal-trigger" href="#{{i.id}}">Application</a>
                     <!-- <a class="waves-effect waves-light btn modal-trigger" href="#modal2">Modal</a> -->
                         </div>
                     <!-- Application:- {{i.application}}<br><br> -->
                     Date request raised:- {{i.issued_on}} <br>
                     Requested by:- {{i.request_by}}<br>
                     </div>
                         <div class="card-action">
                           <form method='post'>
                               {% csrf_token %}
                               
                                <a href="#"><button type="submit" value='{{i.id}}' name='id' class="btn waves-effect waves-light">Approv</button>
                                  </a>
                           </form>
                         </div>
                   </div>
                 </div>
               </div>
               </div>

               <!-- Modal Structure -->
               <div id="{{i.id}}" class="modal modal-fixed-footer">
                 <div class="modal-content">
                   <h4>Application</h4>
                   <p>{{i.application}}</p>
                 </div>
                 <div class="modal-footer">
                   <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">ok</a>
                 </div>
               </div>


        {% endif %}

        {% endfor %}

        <br>
        <br>
        <br>
        <center>
            
        <h3>ISSUE HISTORY</h3>
        </center>
        {% for i in data %}
        <div align="center">
        <div class="row" >
                 <div class="col s4 offset-s4 valign">
                   <div class="card"><br>
                       <span class="card-title"><h5>Subject :- {{i.subject}} </h5></span>
                     <div class="card-content">
                         <div class="card-action">

                           <a class ="modal-trigger" href="#{{i.id}}">Application</a>
                     <!-- <a class="waves-effect waves-light btn modal-trigger" href="#modal2">Modal</a> -->
                         </div>
                     <!-- Application:- {{i.application}}<br><br> -->
                     Date_issued:- {{i.issued_on}} <br>
                     Issued_by:- {{i.request_by}}<br>
                     </div>
                         
                   </div>
                 </div>
               </div>
               </div>

               <!-- Modal Structure -->
               <div id="{{i.id}}" class="modal modal-fixed-footer">
                 <div class="modal-content">
                   <h4>Application</h4>
                   <p>{{i.application}}</p>
                 </div>
                 <div class="modal-footer">
                   <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">ok</a>
                 </div>
               </div>

        {% endfor %}

{% endblock %}

templates/inventory/update.html
<html>
	<head>
		<title>
			INVENTORY UPDATE
		</title>
	</head>

	<body>
		<center>
			Update Inventory
		</center>
		<br>

		{% if selection0 %}
		Option selected- {{choice}}
		{% else %}
		<h2>Make selection</h2>
		<form method='get'>
			<select name='choice'>
				<option value='old'>Update existing Inventory</option>
				<option value'=new'>Add new items to Inventory</option>
			</select>
			<br><br>
			<button type='submit'> SUBMIT </button>
		</form>
		{% endif %}

		{% if selection0 %}
		<h1>
			Select storage location
		</h1><br><br>
		<form method='get'>
			{% if selection1 %}
			Location selected- {{location}}
			{% else %}
			<select name='location'>
				{% for i in data %}
				<option value='{{i.location}}' name='location'>{{i.location}}</option>
				{% endfor %}
				<option value='another_loc'> Another </option>
			</select>
			<button type='submit' value='{{choice}}' name='choice'> SUBMIT </button>
			{% endif %}
		</form>
		{% endif %}
			{% block content %}
			{% endblock %}
	</body>
</html>

templates/inventory/update_new.html
{% extends 'inventory/update.html' %}
{% load static %}
{% block content %}
<br>
	<br>
	{% if selection1 %}
	<h3>Enter the details</h3>
	<form method='post'>
		{% csrf_token %}
		<h4>NOTE- TYPE 0 in fields which are not required</h4>
		<input name='bot_name' placeholder="Enter the bot details"> &nbsp&nbsp&nbsp&nbsp
		<input name='bot_count' placeholder="Enter the bot count"><br>
		<br>
		<select name="successor_bot">
			{% for i in location.inventory_set.all %}
			<option value='{{i.bot_name}}'>{{i.bot_name}}</option>
			{% endfor %}
		</select>
			<input name='accessory' placeholder="Enter name of accessory to be added"> &nbsp&nbsp&nbsp&nbsp
			<input name='count' placeholder="Enter the accessory count"> <br><br>
		<input type="hidden" name='choice' value='{{choice}}'>
		<button type='submit' value='{{location}}' name='location'> SUBMIT </button>
	</form>
	{% endif %}
{% endblock %}

templates/inventory/update_old.html
{% extends 'inventory/update.html' %}
{% load static %}
{% block content %}
<br>
	<br>
	{% if selection1 %}
<h3>After selecting location, update inventory</h3>
<form method='post'>
	{% csrf_token %}
	<h4><p>Name 							Count</p></h4>
	{% for i in location.inventory_set.all %}
	<input value='{{i.bot_name}}' name="bot_name"> &nbsp &nbsp &nbsp
	<input value='{{i.bot_count}}' name="bot_count"><br>
	{% endfor %}
	<h3>Update accessories</h3>
	{% for i in location.accessories_set.all %}
	<input value="{{i.accessory}}" name='accessory'> &nbsp &nbsp &nbsp
	<input value='{{i.count}}' name='count'> <br>
	{% endfor %}
	<input type="hidden" name='choice' value='{{choice}}'>
	<br>
	<br>
	<button type='submit' value='{{location}}' name='location'> SAVE </button>
</form>
{% endif %}
{% endblock %}