access/urls.py
from django.conf.urls import url
from . import views

app_name = 'access'
urlpatterns = [
	url(r'^login/',views.login,name='login'),
	url(r'^logout/',views.logout,name='logout'),
	url(r'^signup/',views.signup,name='signup'),
]

base/urls.py
from django.conf.urls import url
from . import views

app_name = 'base'
urlpatterns = [
	url(r'^$',views.index,name="index"),
	url(r'^profile/',views.profile,name="profile"),
]

inventory/urls.py
from django.conf.urls import url
from . import views

app_name = 'inventory'
urlpatterns = [
	url(r'^$',views.index,name="inventory_index"),
	url(r'^update/',views.update,name='update'),
	url(r'^update/.*',views.update,name='update'),
	url(r'^issue/',views.issue,name='issue'),
	url(r'^requests/',views.list_requests,name='requests'),
]

projects/urls.py
from django.conf.urls import url
from . import views

app_name = 'projects'
urlpatterns = [
	url(r'^$',views.index,name='projects_index'),
	url(r'^add/',views.add,name='add'),
]

the_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('base.urls', namespace='base_app')),
    url(r'^site/',include('access.urls', namespace='access')),
    url(r'^inventory/',include('inventory.urls', namespace='inventory')),
    url(r'^projects/',include('projects.urls', namespace='projects')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from inventory import models
# Create your views here.

def index(request):
	return(render(request,'base/home.html',{}))

def profile(request):
	user = get_object_or_404(User,pk=request.user.id)
	# state,issues = get_object_or_404(models.issue_application,request_by__pk=request.user.id)
	issues = models.issue_application.objects.all().filter(request_by__id=request.user.id)
	context = {'user':user,'issues':issues}
	return(render(request,'base/profile.html',context))

templates/base/home.html
{% extends 'base/index.html' %}
{% load static %}
{% block content %}
<div align="center">
   <!--<img  src={% static "assets/logo.png" %} alt="LOGO" style="width:300px;height:172px;">-->
<div class="row" >
         <div class="col s6 offset-s3 valign">
           <div class="card">
             <div class="card-image">
               <img src={% static "assets/robo.jpg" %}>
               <span class="card-title"><h2>e-Yantra Robotics Competition</h2></span>
             </div>
             <div class="card-content">
               <h3>e-YRC</h3>
               <p>e-Yantra Robotics Competition (eYRC) is a unique annual competition for undergraduate students in science and colleges. Selected teams are given a robotic kit complete with accessories and video tutorials to help them learn basic concepts in embedded systems and microcontroller programming. Abstracts of real world problems assigned as "themes" are then implemented by the teams using the robotic kits. The winners of this competition will be eligible for summer internship at IITB through e-Yantra Summer Internship Program .</p>
             </div>
             <div class="card-action">
               <a href="#">More</a>
             </div>
           </div>
         </div>
       </div>
       </div>


{% endblock %}

templates/base/index.html
 {% load static %}
 <!DOCTYPE html>
  <html>
	<head><title>Base Page</title>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	  <!--Import Google Icon Font-->
	  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	  <!--Import materialize.css-->
	  <link type="text/css" rel="stylesheet" href= {% static "css/materialize.min.css" %}  media="screen,projection"/>

	  <!--Let browser know website is optimized for mobile-->
	  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	  
	<style>
      .modal {width: 30% !important; height: 60% !important;}
      html,
      body {
          height: 100%;
          margin: 0;
          padding: 0;
      }
      #main-wrapper {
          min-height: 100%;
          padding: 0 0 200px;
          position: relative;
      }
      footer {
          bottom: 0;
          height: 200px;
          left: 0;
          position: absolute;
          width: 100%;
      }
    </style>
    
    </head>
    <body background={% static "assets/bg.jpg" %}>

<div id="main-wrapper">
	<nav>
    	<div class="nav-wrapper">
    	  <a href="{% url 'base:index' %}" class="brand-logo"><img src={% static "assets/logo.png" %} alt="Logo" style="width:100px;height:64px;"></a>
    	  <ul id="nav-mobile" class="right hide-on-med-and-down">
    		<li><a class='dropdown-button' href='#' data-activates='dropdown1'>Inventory</a></li>
            <li><a class='dropdown-button' href='#' data-activates='dropdown2'>Projects</a></li>
    		<!-- <li><a class="waves-effect waves-light" href="team/">Team</a></li> -->
    		{% if user.is_authenticated %}
    		<li> <a class="waves-effect waves-light modal-trigger" href="{% url 'base:profile' %}">{{user.username}}</a></li>
    		<li> <a class="waves-effect waves-light modal-trigger" href="{% url 'access:logout' %}">Logout</a></li>
    		{% else %}
    		<li> <a class="waves-effect waves-light modal-trigger" href="#modal1">Log In</a></li>
    		<li><a class="waves-effect waves-light" href="{% url 'access:signup' %}">Sign Up</a></li>
    	  	{% endif %}
    	  </ul>
    	</div>
    </nav>

   <ul id='dropdown2' class='dropdown-content'>
      <li><a href="{% url 'projects:projects_index' %}">Projects</a></li>
      <li><a href="{% url 'projects:add' %}">Add</a></li>
    </ul>


    <!-- Dropdown Structure -->
    <ul id='dropdown1' class='dropdown-content'>
        <li><a href="{% url 'inventory:inventory_index' %}">Inventory</a></li>
        <li><a href="{% url 'inventory:issue' %}">Issue</a></li>
        <li><a href="{% url 'inventory:requests' %}">Request</a></li>
        <li><a href="{% url 'inventory:update' %}">Update</a></li>
    </ul>

	<!-- Modal Structure -->
	<div id="modal1" class="modal">
	  <div class="modal-content">
	    <div class="row">
	       <form class="col s10 offset-s1 valign" method='post' action="{% url 'access:login' %}">
	       {% csrf_token %}
	       <center>
	         <h3>Log In</h3>
	       </center>
	           <div class="input-field col s12">
	             <i class="material-icons prefix">tag_faces</i>
	             <input type = 'text' name='username' placeholder='Username'><br><br>
	           </div>
	           <div class="input-field col s12">
	             <i class="material-icons prefix">border_color</i>
	             <input type='password' name='password' placeholder='Password'><br><br>
	            </div>
	            <center>
	            <!-- <input type='button' onclick="window.location.href='site/login/'"> -->
	            <button type='submit' class="btn waves-effect waves-light">Submit</button>
	              </center>
	       </form>
	     </div>
	   </div>
	</div>

    <div>
      	{% if msg %}
      	<center>{{msg}}</center>
      	{% endif %}
      	{% for i in error_details %}
      	<center>{{i}}</center>
      	{% endfor %}

    	{% block content %}
    	{% endblock %}
    </div>

	<footer class="page-footer">
			   <div class="container">
				 <div class="row">
				   <div class="col l6 s12">
					 <h5 class="white-text">Footer Content</h5>
					 <p class="grey-text text-lighten-4"></p>
				   </div>
				   <div class="col l4 offset-l2 s12">
					 <h5 class="white-text">Contact Us</h5>
					 <ul>
					   <li><a class="grey-text text-lighten-3" href="#!"></a>Facebook</li>
					   <li><a class="grey-text text-lighten-3" href="#!"></a>Twitter</li>
					   
					 </ul>
				   </div>
				 </div>
			   </div>
			   <div class="footer-copyright">
				 <div class="container">
				 © 2017 Copyright
				 <a class="grey-text text-lighten-4 right" href="#!">$</a>
				 </div>
			   </div>
	</footer>
</div>
	<!--Import jQuery before materialize.js-->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script type="text/javascript" src={% static "js/materialize.min.js" %} ></script>
	<script>
  $(document).ready(function(){
	  // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
	  $('.modal').modal();
	});
	
          $('.dropdown-button').dropdown({
        inDuration: 300,
        outDuration: 225,
        constrainWidth: false, // Does not change width of dropdown to that of the activator
        hover: true, // Activate on hover
        gutter: 0, // Spacing from edge
        belowOrigin: false, // Displays dropdown below the button
        alignment: 'left', // Displays dropdown with edge aligned to the left of button
        stopPropagation: false // Stops event propagation
      }
    );
	</script>
	</body>
  </html>

templates/base/profile.html
{% extends 'base/index.html' %}
{% load static %}
{% block content %}
    <div class="row">
          <div class="col s6 offset-s3 valign">
            <div class="card-panel grey lighten-4">
              <center>
                <form method = 'post'>
                    {% csrf_token %}
                    <h4>Update Info</h4>
                    <div class="input-field col s6">
                      <i class="material-icons prefix">person</i>
                      <input type = 'text' name='first_name' placeholder='First Name ({{user.first_name}})'><br><br>
                    </div>
                    <div class="input-field col s6">
                      <!-- <i class="material-icons prefix">tag_faces</i> -->
                      <input type = 'text' name='last_name' placeholder='Last Name ({{user.last_name}})'><br><br>
                    </div>
                    <div class="input-field col s12">
                      <i class="material-icons prefix">contact_mail</i>
                      <!-- <input type = 'text' name='username' placeholder='Username'><br><br> -->
                      <input type='email' id='email' name='email' placeholder="Email ID ({{user.email}})"><br><br>
                    </div>
                    <div class="input-field col s12">
                      <i class="material-icons prefix">tag_faces</i>
                      <input type = 'text' name='username' placeholder='Username ({{user.username}})'><br><br>
                    </div>
                    <center>
                    <a href="#"><button type="submit" class="btn waves-effect waves-light">Update</button>
                      </a></center>
                   
                </form>
            </center>

              
            </div>
          </div>
        </div>
        <center>
        <h3>Issue Applcations</h3>
            
        </center>
        {% for i in issues %}
        <div align="center">
        <div class="row" >
                 <div class="col s4 offset-s4 valign">
                   <div class="card"><br>
                   
                       <span class="card-title"><h5>Subject :- {{i.subject}} </h5></span>
                     <div class="card-content">
                         <div class="card-action">

                           <a class ="modal-trigger" href="#{{i.id}}">Application</a>
                     <!-- <a class="waves-effect waves-light btn modal-trigger" href="#modal2">Modal</a> -->
                         </div>
                     <!-- Application:- {{i.application}}<br><br> -->
                     PUBLISHED DATE:- {{i.issued_on}} <br>
                     Approved? {% if i.passed %}
                     Yes
                     {% else %}
                     No
                     {% endif %}
                     <br>
                     </div>
                         
                   </div>
                 </div>
               </div>
               </div>

               <!-- Modal Structure -->
               <div id="{{i.id}}" class="modal modal-fixed-footer">
                 <div class="modal-content">
                   <h4>Application</h4>
                   <p>{{i.application}}</p>
                 </div>
                 <div class="modal-footer">
                   <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">ok</a>
                 </div>
               </div>

        {% endfor %}






{% endblock %}